# Generated by Django 5.1.3 on 2025-01-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0002_category_tag_product_category_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='barcode_num',
            field=models.IntegerField(),
        ),
    ]
